
CREATE TABLE IF NOT EXISTS doctors (
    doctor_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    specialization VARCHAR(50) CHECK (specialization IN (
        'THERAPIST',
        'DENTIST',
        'OPHTHALMOLOGIST',
        'CARDIOLOGIST',
        'ENDOCRINOLOGIST'
    ))
);

